


pub enum KeyCode {
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    Snapshot,

    Scroll,

    Pause,

    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,

    Left,
    Up,
    Right,
    Down,


    Back,

    Return,

    Space,

    Compose,

    Caret,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,

    AbntC1,
    AbntC2,
    Add,
    Apostrophe,
    Apps,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Decimal,
    Divide,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Multiply,
    Mute,
    MyComputer,

    NavigateForward,

    NavigateBackward,
    NextTrack,
    NoConvert,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    OEM102,
    Period,
    PlayPause,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Subtract,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

pub fn virtual_to_keycode(virtual_keycode: VirtualKeyCode) -> KeyCode {
    match virtual_keycode {
        VirtualKeyCode::Key1 => KeyCode::Key1, 
        VirtualKeyCode::Key2 => KeyCode::Key2,
        VirtualKeyCode::Key3 => KeyCode::Key3,
        VirtualKeyCode::Key4 => KeyCode::Key4,
        VirtualKeyCode::Key5 => KeyCode::Key5,
        VirtualKeyCode::Key6 => KeyCode::Key6,
        VirtualKeyCode::Key7 => KeyCode::Key7,
        VirtualKeyCode::Key8 => KeyCode::Key8,
        VirtualKeyCode::Key9 => KeyCode::Key9,
        VirtualKeyCode::Key0 => KeyCode::Key0,

        VirtualKeyCode::A => KeyCode::A,
        VirtualKeyCode::B => KeyCode::B,
        VirtualKeyCode::C => KeyCode::C,
        VirtualKeyCode::D => KeyCode::D,
        VirtualKeyCode::E => KeyCode::E,
        VirtualKeyCode::F => KeyCode::F,
        VirtualKeyCode::G => KeyCode::G,
        VirtualKeyCode::H => KeyCode::H,
        VirtualKeyCode::I => KeyCode::I,
        VirtualKeyCode::J => KeyCode::J,
        VirtualKeyCode::K => KeyCode::K,
        VirtualKeyCode::L => KeyCode::L,
        VirtualKeyCode::M => KeyCode::M,
        VirtualKeyCode::N => KeyCode::N,
        VirtualKeyCode::O => KeyCode::O,
        VirtualKeyCode::P => KeyCode::P,
        VirtualKeyCode::Q => KeyCode::Q,
        VirtualKeyCode::R => KeyCode::R,
        VirtualKeyCode::S => KeyCode::S,
        VirtualKeyCode::T => KeyCode::T,
        VirtualKeyCode::U => KeyCode::U,
        VirtualKeyCode::V => KeyCode::V,
        VirtualKeyCode::W => KeyCode::W,
        VirtualKeyCode::X => KeyCode::X,
        VirtualKeyCode::Y => KeyCode::Y,
        VirtualKeyCode::Z => KeyCode::Z,

        VirtualKeyCode::Escape,

        VirtualKeyCode::F1,
        VirtualKeyCode::F2,
        VirtualKeyCode::F3,
        VirtualKeyCode::F4,
        VirtualKeyCode::F5,
        VirtualKeyCode::F6,
        VirtualKeyCode::F7,
        VirtualKeyCode::F8,
        VirtualKeyCode::F9,
        VirtualKeyCode::F10,
        VirtualKeyCode::F11,
        VirtualKeyCode::F12,
        VirtualKeyCode::F13,
        VirtualKeyCode::F14,
        VirtualKeyCode::F15,
        VirtualKeyCode::F16,
        VirtualKeyCode::F17,
        VirtualKeyCode::F18,
        VirtualKeyCode::F19,
        VirtualKeyCode::F20,
        VirtualKeyCode::F21,
        VirtualKeyCode::F22,
        VirtualKeyCode::F23,
        VirtualKeyCode::F24,

        VirtualKeyCode::Snapshot,

        VirtualKeyCode::Scroll,

        VirtualKeyCode::Pause,

        VirtualKeyCode::Insert,
        VirtualKeyCode::Home,
        VirtualKeyCode::Delete,
        VirtualKeyCode::End,
        VirtualKeyCode::PageDown,
        VirtualKeyCode::PageUp,

        VirtualKeyCode::Left,
        VirtualKeyCode::Up,
        VirtualKeyCode::Right,
        VirtualKeyCode::Down,

        VirtualKeyCode::Back,

        VirtualKeyCode::Return,

        VirtualKeyCode::Space,

        VirtualKeyCode::Compose,

        VirtualKeyCode::Caret,

        VirtualKeyCode::Numlock,
        VirtualKeyCode::Numpad0,
        VirtualKeyCode::Numpad1,
        VirtualKeyCode::Numpad2,
        VirtualKeyCode::Numpad3,
        VirtualKeyCode::Numpad4,
        VirtualKeyCode::Numpad5,
        VirtualKeyCode::Numpad6,
        VirtualKeyCode::Numpad7,
        VirtualKeyCode::Numpad8,
        VirtualKeyCode::Numpad9,

        VirtualKeyCode::AbntC1,
        VirtualKeyCode::AbntC2,
        VirtualKeyCode::Add,
        VirtualKeyCode::Apostrophe,
        VirtualKeyCode::Apps,
        VirtualKeyCode::At,
        VirtualKeyCode::Ax,
        VirtualKeyCode::Backslash,
        VirtualKeyCode::Calculator,
        VirtualKeyCode::Capital,
        VirtualKeyCode::Colon,
        VirtualKeyCode::Comma,
        VirtualKeyCode::Convert,
        VirtualKeyCode::Decimal,
        VirtualKeyCode::Divide,
        VirtualKeyCode::Equals,
        VirtualKeyCode::Grave,
        VirtualKeyCode::Kana,
        VirtualKeyCode::Kanji,
        VirtualKeyCode::LAlt,
        VirtualKeyCode::LBracket,
        VirtualKeyCode::LControl,
        VirtualKeyCode::LShift,
        VirtualKeyCode::LWin,
        VirtualKeyCode::Mail,
        VirtualKeyCode::MediaSelect,
        VirtualKeyCode::MediaStop,
        VirtualKeyCode::Minus,
        VirtualKeyCode::Multiply,
        VirtualKeyCode::Mute,
        VirtualKeyCode::MyComputer,

        VirtualKeyCode::NavigateForward,

        VirtualKeyCode::NavigateBackward,
        VirtualKeyCode::NextTrack,
        VirtualKeyCode::NoConvert,
        VirtualKeyCode::NumpadComma,
        VirtualKeyCode::NumpadEnter,
        VirtualKeyCode::NumpadEquals,
        VirtualKeyCode::OEM102,
        VirtualKeyCode::Period,
        VirtualKeyCode::PlayPause,
        VirtualKeyCode::Power,
        VirtualKeyCode::PrevTrack,
        VirtualKeyCode::RAlt,
        VirtualKeyCode::RBracket,
        VirtualKeyCode::RControl,
        VirtualKeyCode::RShift,
        VirtualKeyCode::RWin,
        VirtualKeyCode::Semicolon,
        VirtualKeyCode::Slash,
        VirtualKeyCode::Sleep,
        VirtualKeyCode::Stop,
        VirtualKeyCode::Subtract,
        VirtualKeyCode::Sysrq,
        VirtualKeyCode::Tab,
        VirtualKeyCode::Underline,
        VirtualKeyCode::Unlabeled,
        VirtualKeyCode::VolumeDown,
        VirtualKeyCode::VolumeUp,
        VirtualKeyCode::Wake,
        VirtualKeyCode::WebBack,
        VirtualKeyCode::WebFavorites,
        VirtualKeyCode::WebForward,
        VirtualKeyCode::WebHome,
        VirtualKeyCode::WebRefresh,
        VirtualKeyCode::WebSearch,
        VirtualKeyCode::WebStop,
        VirtualKeyCode::Yen,
        VirtualKeyCode::Copy,
        VirtualKeyCode::Paste,
        VirtualKeyCode::Cut,
    }
}