use tuix::*;
use fnv::FnvHashMap;
use std::{any::Any, collections::HashSet, hash::Hash};

static THEME: &'static str = include_str!("themes/counter_theme.css");


#[derive(Default)]
pub struct CounterState {
    value: i32,
}

//////////////////////////////////////////////////
// This code will be generated by a derive macro
impl Node for CounterState {}


#[derive(Default)]
pub struct GeneratedLens_CounterState_value;

impl GeneratedLens_CounterState_value {
    pub const fn new() -> Self {
        Self {}
    }
}

impl CounterState {
    pub const value: GeneratedLens_CounterState_value = GeneratedLens_CounterState_value::new();
}

impl Lens for GeneratedLens_CounterState_value {
    type Source = CounterState;
    type Target = i32;

    fn view(&self, data: &Self::Source) -> Self::Target {
        data.value
    }
}
////////////////////////////////////////////////

////////////////////////////////////////////////
// This boilerplate code will be part of the library
pub struct Store<D> {
    data_widget: D,
    observers: HashSet<Entity>,
}

impl<D: Widget> Store<D> {
    pub fn new(data_widget: D) -> Self {
        Self {
            data_widget,
            observers: HashSet::new(),
        }
    }
}

impl<D: Widget + Node> Widget for Store<D> {
    type Ret = <D as Widget>::Ret;
    type Data = ();
    fn on_build(&mut self, state: &mut State, entity: Entity) -> Self::Ret {
        self.data_widget.on_build(state, entity)
    }

    fn on_event(&mut self, state: &mut State, entity: Entity, event: &mut Event) {
        
        if let Some(bind_event) = event.message.downcast() {
            match bind_event {
                BindEvent::Bind(target) => {
                    self.observers.insert(*target);
                }

                BindEvent::Update => {

                    for observer in self.observers.iter() {
                        if let Some(mut event_handler) = state.event_handlers.remove(observer) {
                            event_handler.on_update(state, *observer, &self.data_widget);

                            state.event_handlers.insert(*observer, event_handler);
                        }
                    }
                }
            }
        }

        self.data_widget.on_event_(state, entity, event);
    }
}
//////////////////////////////////////////////


#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CounterMessage {
    Increment,
    Decrement,
}

impl Widget for CounterState {
    type Ret = Entity;
    type Data = ();

    fn on_build(&mut self, state: &mut State, entity: Entity) -> Self::Ret {
        entity
    }

    fn on_event(&mut self, state: &mut State, entity: Entity, event: &mut Event) {
        if let Some(counter_event) = event.message.downcast() {
            match counter_event {
                CounterMessage::Increment => {
                    self.value += 1;
                    entity.emit(state, BindEvent::Update);
                    event.consume();
                }

                CounterMessage::Decrement => {
                    self.value -= 1;
                    entity.emit(state, BindEvent::Update);
                    event.consume();
                }
            }            
        }
    }
}



#[derive(Default)]
struct CounterWidget {

}

impl CounterWidget {

    pub fn new() -> Self {
        Self {

        }
    }
}

impl Widget for CounterWidget {
    type Ret = Entity;
    type Data = CounterState;

    fn on_build(&mut self, state: &mut State, entity: Entity) -> Self::Ret {

        Button::with_label("increment")
            .on_press(|_, state, button|{
                button.emit(state, CounterMessage::Increment);
            })
            .build(state, entity, |builder| builder.class("increment"));

        Button::with_label("decrement")
            .on_press(|_, state, button|{
                button.emit(state,  CounterMessage::Decrement);
            })
            .build(state, entity, |builder| builder.class("decrement"));

        Label::new("0")
            .bind(CounterState::value, |value| value.to_string())
            .build(state, entity, |builder| builder);

        entity.set_element(state, "counter").set_layout_type(state, LayoutType::Row)
    }
}

fn main() {
    // Create the app
    let window_description = WindowDescription::new().with_title("Counter").with_inner_size(400, 100);
    let app = Application::new(window_description, |state, window| {
        state.add_theme(THEME);

        let data_widget = Store::new(CounterState::default()).build(state, window, |builder| builder);

        CounterWidget::new()
            .build(state, data_widget, |builder| builder);

        CounterWidget::new()
            .build(state, data_widget, |builder| builder);
        
        Label::new("Zero")
            .bind(CounterState::value, |value| english_numbers::convert_all_fmt(*value as i64))
            .build(state, data_widget, |builder| 
                builder
                    .set_width(Stretch(1.0))
                    .set_space(Pixels(5.0))
            );
    });

    app.run();
}
